import numpy as np
from pathlib import Path

script_dir = Path(__file__).resolve().parent
# output_path = script_dir.parent / "rtl" / "atan_table.mem"
header_path = script_dir.parent / "rtl" / "cordic_constants.svh"
# A .svh file is a SystemVerilog Header file used in hardware description 
# and verification environments to hold reusable code blocks, definitions, macros, and class declarations

# output_path.parent.mkdir(parents=True, exist_ok=True)
header_path.parent.mkdir(parents=True, exist_ok=True)

N_STAGES    = 16
PHASE_WIDTH = 32
OUT_WIDTH   = 14
GUARD_BITS  = 4                 # extra internal precision due to rounding errors after N_stages of CORDIC
WORK_WIDTH  = OUT_WIDTH + GUARD_BITS

# Calc of atan LUT: arctan(2^-i) table, accounting for size of z.
# scale atan values such that largest signed WORKING_WIDTH bits integer is equal to pi/2!
atan_vals = np.arctan(2.0 ** -np.arange(N_STAGES))
atan_scaled = np.round(atan_vals / (np.pi / 2) * (2 ** (WORK_WIDTH - 1))).astype(int)
# take 2**(width-1) as weight and not 2**(width-1) -1 as weight although is largest 2compl number
# -> Can see it as inheritance from phase. bit k of phase always carries a weight of (360°/2^32) × 2^k. phase[31] is 180 degrees. 
#    Look at sign bit of z, i.e. phase[30] then this has weight of 90 degrees. So need to scale to that bit, i.e. 2^(WORK_WIDTH-1)
# -> Can also see this since pi/2 and -pi/2 are given by 10...0 and thus are the smallest negative number in twos complement (i.e. -2^(WORK_WIDTH-1))
#    So scale to that, then our range is [-pi/2,pi/2)!

# Use for test bench
# with open("atan_table.mem", "w") as f:
#     for v in atan_scaled:
#             f.write(f"{v & (2**WORK_WIDTH - 1):0{(WORK_WIDTH+3)//4}x}\n")
            # v & (2**WORK_WIDTH - 1) -> bitwise AND with 0000111...1 with WORK_WIDTH many 1s to make the python integer v fixed width (WORK_WIDTH)
            #                            this is exactly the size of z in the CORDIC stages!
            # :0{(WORK_WIDTH+3)//4}x  -> specifies Python's f-string format specification. x at the end makes it hexadecimal rather than default decimal.
            # {(WORK_WIDTH+3)//4}x}   -> number of hex digits needed to represent WORK_WIDTH bits.    

# with open(output_path, "w") as f:
#     for v in atan_scaled:
#         f.write(f"{v & (2**WORK_WIDTH - 1):0{(WORK_WIDTH+3)//4}x}\n")
        # v & (2**WORK_WIDTH - 1) -> bitwise AND with 0000111...1 with WORK_WIDTH many 1s to make the python integer v fixed width (WORK_WIDTH)
        #                            this is exactly the size of z in the CORDIC stages!
        # :0{(WORK_WIDTH+3)//4}x  -> specifies Python's f-string format specification. x at the end makes it hexadecimal rather than default decimal.
        # {(WORK_WIDTH+3)//4}x}   -> number of hex digits needed to represent WORK_WIDTH bits.    

# Calcualte CORDIC gain and the gain-precorrected initial x
K = np.prod(np.cos(atan_vals[:N_STAGES]))
print(f"CORDIC gain K = {K:.6f}")

# scale 1 to full work width
work_full_scale = 2 ** (WORK_WIDTH - 1) - 1
x0 = round(K * work_full_scale)

print(f"X0 (WORK_WIDTH={WORK_WIDTH}) = {x0}")
print(f"localparam signed [{WORK_WIDTH-1}:0] X0 = {WORK_WIDTH}'sd{x0};")
# sd stands for signed decimal



### pack LUT values into one string
mask    = 2 ** WORK_WIDTH - 1   # geenrates 0x3FFFF number, lowest 18 bits are all ones to use bitwise and & later for isolating lowest 18 bits
hexw    = (WORK_WIDTH + 3) // 4 # number of hex digits needed for 18 bits, // is integer division, so no decimals created by this
entries = [f"{WORK_WIDTH}'h{int(v) & mask:0{hexw}x}" for v in atan_scaled]
# is a list comprehension: loops over the numbers in atan_scaled, in order, and builds one string per number
# :0{hexw}x is the format specification: x = lowercase hex, 0 = pad with zeros, width = hexw = 5, i.e. :05x
# assembled string is 18'h09720 for example
concat  = ",\n    ".join(reversed(entries))
# reverse order of list, because in system verilog concatenation {a, b, c}, the leftmost item lands in the MSB
# {C, B, A}   ->   bits [11:8] = C,  [7:4] = B,  [3:0] = A
# ",\n ".join(...) glues the strings together with a comma, a newline and four spaces between them
# -> spaces are only cosmetic

with open(header_path, "w") as f:
    f.write("// auto-generated by scripts/gen_cordic_constants.py -> do not edit by hand\n")   # Verilog comment
    f.write("// Rerun whenever N_STAGES | OUT_WIDTH | GUARD_BITS change\n")
    f.write(f"`define CORDIC_GEN_N_STAGES   {N_STAGES}\n")  # SV that defines a text macro, to later check if generated and used values are based on the same hardware parameters
    f.write(f"`define CORDIC_GEN_OUT_WIDTH  {OUT_WIDTH}\n") # so if I write CORDIC_GEN_OUT_WIDTH in .sv file will be replaced by number OUT_WIDTH
    f.write(f"`define CORDIC_GEN_GUARD_BITS {GUARD_BITS}\n\n")  # https://chipverify.com/systemverilog/systemverilog-define-macro
    f.write(f"localparam signed [{WORK_WIDTH-1}:0] X0 = {WORK_WIDTH}'sd{x0};\n\n")  # sv command to declare the X0 parameter
    f.write(f"// ATAN_FLAT[i*{WORK_WIDTH} +: {WORK_WIDTH}] = atan LUT entry i, i = 0 .. {N_STAGES-1}.\n")   # comments for indexing rule
    f.write("// Entry 0 occupies the lowest bits, thus the concatenation lists entry N-1 first\n")  # vector[base +: width]   =   bits  base  up to  base + width - 1
    f.write(f"localparam logic [{N_STAGES*WORK_WIDTH-1}:0] ATAN_FLAT = {{\n    {concat}\n}};\n")
    # {{ is the literal curly brace in python 
    # {concat} inserts variable
    # will look like:
    # localparam logic [287:0] ATAN_FLAT = {
    #       18'h00003,
    #       18'h00005,
    #        ...
    #       18'h09720,
    #       18'h10000
    #   };






# save x0 in header file. then can check in .sv file if x0 generated for right parameters and directly read x0
# with open(header_path, "w") as f:
#     f.write("// AUTO-GENERATED by scripts/gen_cordic_constants.py — do not edit by hand\n")
#     f.write("// Regenerate whenever N_STAGES / OUT_WIDTH / GUARD_BITS change.\n")
#     f.write(f"`define CORDIC_GEN_N_STAGES   {N_STAGES}\n")
#     f.write(f"`define CORDIC_GEN_OUT_WIDTH  {OUT_WIDTH}\n")
#     f.write(f"`define CORDIC_GEN_GUARD_BITS {GUARD_BITS}\n")
#     f.write(f"localparam signed [{WORK_WIDTH-1}:0] X0 = {WORK_WIDTH}'sd{x0};\n")

