// AUTO-GENERATED by scripts/gen_cordic_constants.py — do not edit by hand
// Regenerate whenever N_STAGES / OUT_WIDTH / GUARD_BITS change.
`define CORDIC_GEN_N_STAGES   16
`define CORDIC_GEN_OUT_WIDTH  14
`define CORDIC_GEN_GUARD_BITS 4
localparam signed [17:0] X0 = 18'sd79593;
