// auto-generated by scripts/gen_cordic_constants.py -> do not edit by hand
// Rerun whenever N_STAGES | OUT_WIDTH | GUARD_BITS change
`define CORDIC_GEN_N_STAGES   16
`define CORDIC_GEN_OUT_WIDTH  14
`define CORDIC_GEN_GUARD_BITS 4

localparam signed [17:0] X0 = 18'sd79593;

// ATAN_FLAT[i*18 +: 18] = atan LUT entry i, i = 0 .. 15.
// Entry 0 occupies the lowest bits, thus the concatenation lists entry N-1 first
localparam logic [287:0] ATAN_FLAT = {
    18'h00003,
    18'h00005,
    18'h0000a,
    18'h00014,
    18'h00029,
    18'h00051,
    18'h000a3,
    18'h00146,
    18'h0028c,
    18'h00518,
    18'h00a2f,
    18'h01458,
    18'h02889,
    18'h04fda,
    18'h09720,
    18'h10000
};
